import {useState} from 'react';
import type {State,Editor,Row} from './types';
import {dollars,words} from './types';
import {post} from './api';
import {Empty,Icon,Field,Form,ErrorText} from './ui';

export function Jobs({state,isToday,onEdit,selected,onSelect,onReload,onReceipt}:{state:State;isToday:boolean;onEdit:(editor:Editor)=>void;selected:string|null;onSelect:(id:string|null)=>void;onReceipt:(row:Row)=>void;onReload:()=>Promise<void>}) {
  const [query,setQuery]=useState(''),[filter,setFilter]=useState('all');
  const job=state.jobs.find(j=>j.id===selected);
  if(job)return <JobDetail job={job} state={state} onEdit={onEdit} onBack={()=>onSelect(null)} onReload={onReload} onReceipt={onReceipt}/>;
  const jobs=state.jobs.filter(j=>(!isToday||!['completed','archived'].includes(String(j.status)))&&(filter==='all'||j.status===filter)&&`${j.title} ${j.customer_name} ${j.address}`.toLowerCase().includes(query.toLowerCase()));
  return <><section className="job-section"><h2>{isToday?'Active jobs':'All jobs'}</h2><div className="list-tools"><label className="search"><Icon name="search"/><input aria-label="Find a job" placeholder="Find a job" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="tabs" aria-label="Job status">{[['all','All'],['scheduled','Scheduled'],['in_progress','In progress']].map(([key,label])=><button key={key} className={filter===key?'active':''} aria-pressed={filter===key} onClick={()=>setFilter(key)}>{label}</button>)}</div></div>
  {!jobs.length?<Empty title={query||filter!=='all'?'No matching jobs':state.me.role==='owner'?'Ready for your first job':'No assigned jobs yet'} action={state.me.role==='owner'&&!query?<button className="primary" onClick={()=>onEdit({kind:state.customers.length?'jobs':'customers'})}>{state.customers.length?'Create a job':'Add a customer'}</button>:undefined}>{state.me.role==='owner'?'Add a customer and job to keep the crew, receipts, and mileage together.':'Jim will assign your work here.'}</Empty>:<div className="job-list">{jobs.map(j=><button className="job-row" key={j.id} onClick={()=>onSelect(j.id)}><span><strong>{j.title}</strong><small>{j.customer_name}{j.address?` · ${j.address}`:''}</small></span><span className="row-meta"><span>{words(j.status)}</span><small>{j.scheduled_date||'Date not set'}</small></span></button>)}</div>}
  </section>{isToday&&<section className="activity"><h2>Recent activity</h2>{!state.activity.length?<p className="muted">Activity will appear as your team adds updates.</p>:state.activity.slice(0,8).map(a=><div className="activity-row" key={a.id}><span>{a.actor} · {a.action}</span><time>{a.created_at} UTC</time></div>)}</section>}</>;
}

function JobDetail({job,state,onEdit,onBack,onReload,onReceipt}:{job:Row;state:State;onEdit:(editor:Editor)=>void;onBack:()=>void;onReceipt:(row:Row)=>void;onReload:()=>Promise<void>}) {
  const [tab,setTab]=useState('Details'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const owner=state.me.role==='owner';
  const expenses=state.expenses.filter(e=>e.job_id===job.id&&e.status!=='void'),invoices=state.invoices.filter(i=>i.job_id===job.id&&i.status!=='void'),miles=state.mileage.filter(m=>m.job_id===job.id&&m.status!=='void');
  const spent=expenses.reduce((s,e)=>s+Number(e.amount_cents),0),paid=invoices.reduce((s,i)=>s+Number(i.paid_cents),0);
  async function save(path:string,data:unknown){setBusy(true);setError('');try{await post(path,data);await onReload();}catch(e){setError(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);}}
  return <section className="job-detail"><button className="text-button" onClick={onBack}><Icon name="back"/>All jobs</button><div className="section-heading"><div><h2>{job.title}</h2><p className="muted">{job.customer_name} · {words(job.status)}</p></div>{owner&&<button onClick={()=>onEdit({kind:'jobs',row:job})}>Edit job</button>}</div><div className="tabs detail-tabs">{['Details','Updates','Expenses','Mileage',...(owner?['Crew']:[])].map(t=><button key={t} className={tab===t?'active':''} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</div><ErrorText message={error}/>
  {tab==='Details'&&<div className="detail-grid"><div><dl><dt>Address</dt><dd>{job.address||'Not added'}</dd><dt>Scheduled</dt><dd>{job.scheduled_date||'Not set'}</dd><dt>Customer phone</dt><dd>{job.customer_phone||'Not added'}</dd><dt>Work details</dt><dd className="preserve">{job.scope||'No work details yet.'}</dd></dl><h3>Crew</h3><p>{state.assignments.filter(a=>a.job_id===job.id).map(a=>a.name).join(', ')||'No crew assigned.'}</p></div>{owner&&<aside className="financial-summary"><h3>Job finances</h3><dl><dt>Quoted</dt><dd>{dollars(job.quoted_cents)}</dd><dt>Recorded payments</dt><dd>{dollars(paid)}</dd><dt>Recorded expenses</dt><dd>{dollars(spent)}</dd><dt>Payments less expenses</dt><dd>{dollars(paid-spent)}</dd></dl><small>Based on entered records only. Not a complete accounting profit calculation.</small><h3>Private notes</h3><p className="preserve">{job.owner_notes||'No private notes.'}</p><button onClick={()=>onEdit({kind:'invoices',jobId:job.id})}>Record invoice</button></aside>}</div>}
  {tab==='Updates'&&<><Form onSubmit={data=>{void save(`jobs/${job.id}/notes`,{id:crypto.randomUUID(),body:data.get('body')});}}><Field label="Add a job update"><textarea name="body" required rows={3} maxLength={4000}/></Field><button className="primary" disabled={busy}>{busy?'Saving…':'Post update'}</button></Form><div className="notes">{state.notes.filter(n=>n.job_id===job.id).map(n=><article key={n.id}><p className="preserve">{n.body}</p><small>{n.author} · {n.created_at} UTC</small></article>)}</div></>}
  {tab==='Expenses'&&<><div className="section-heading"><p>{owner?'Job expenses':'Your submissions for this job'}</p><button className="primary" onClick={()=>onEdit({kind:'expenses',jobId:job.id})}>Add expense</button></div>{expenses.length?expenses.map(e=><div className="record-row" key={e.id}><span><strong>{e.vendor}</strong><small>{e.date} · {e.category} · {e.submitted_by}</small></span><span>{dollars(e.amount_cents)}{(owner||e.status==='submitted')&&<button onClick={()=>onEdit({kind:'expenses',row:e})}>Edit</button>}{(e.receipt_id||owner||e.status==='submitted')&&<button onClick={()=>onReceipt(e)}>{e.receipt_id?'Receipt':'Add receipt'}</button>}</span></div>):<Empty title="No expenses recorded"/>}</>}
  {tab==='Mileage'&&<><div className="section-heading"><p>{owner?'Job mileage':'Your mileage for this job'}</p><button className="primary" onClick={()=>onEdit({kind:'mileage',jobId:job.id})}>Log mileage</button></div>{miles.length?miles.map(m=><div className="record-row" key={m.id}><span><strong>{m.vehicle} · {((Number(m.end_tenths)-Number(m.start_tenths))/10).toFixed(1)} miles</strong><small>{m.date} · {m.purpose}</small></span><button onClick={()=>onEdit({kind:'mileage',row:m})}>Edit</button></div>):<Empty title="No mileage recorded"/>}</>}
  {tab==='Crew'&&owner&&<Form onSubmit={data=>{void save(`jobs/${job.id}/assignments`,{users:data.getAll('crew')});}}><p>Only assigned crew members can see this job.</p>{state.team.filter(u=>u.active&&u.role==='crew').map(u=><label className="check" key={u.id}><input type="checkbox" name="crew" value={u.id} defaultChecked={state.assignments.some(a=>a.job_id===job.id&&a.user_id===u.id)}/>{u.name}</label>)}{!state.team.some(u=>u.role==='crew'&&u.active)&&<p className="muted">Add crew accounts in Team first.</p>}<button className="primary" disabled={busy}>{busy?'Saving…':'Save assignments'}</button></Form>}
  </section>;
}
