import {useState} from 'react';
import type {State,Editor,Row} from './types';
import {dollars,words} from './types';
import {Empty,ErrorText,Modal} from './ui';
import {ImportPanel} from './ImportPanel';
import {post} from './api';
export function Money({state,onEdit,onReceipt,onReload}:{state:State;onEdit:(e:Editor)=>void;onReceipt:(r:Row)=>void;onReload:()=>Promise<void>}) {
  const [tab,setTab]=useState('expenses'),[showImport,setShowImport]=useState(false),[error,setError]=useState(''),[undo,setUndo]=useState<string|null>(null),[busy,setBusy]=useState(false);
  const expenses=state.expenses.filter(e=>e.status!=='void'),invoices=state.invoices.filter(i=>i.status!=='void');
  const spent=expenses.reduce((s,e)=>s+Number(e.amount_cents),0),paid=invoices.reduce((s,i)=>s+Number(i.paid_cents),0),outstanding=invoices.reduce((s,i)=>s+Number(i.total_cents)-Number(i.paid_cents),0);
  const rows=tab==='expenses'?state.expenses:tab==='mileage'?state.mileage:state.invoices;
  async function undoBatch(){if(!undo)return;setBusy(true);setError('');try{await post(`import/${undo}/undo`,{});await onReload();setUndo(null);}catch(e){setError(e instanceof Error?e.message:'Could not undo.');}finally{setBusy(false);}}
  return <><div className="totals"><div><span>Recorded payments</span><strong>{dollars(paid)}</strong></div><div><span>Recorded expenses</span><strong>{dollars(spent)}</strong></div><div><span>Unpaid invoice balance</span><strong>{dollars(outstanding)}</strong></div></div><p className="muted">All entered records, excluding voids. These totals are not a full set of accounting books.</p><div className="section-heading"><div className="tabs">{['expenses','mileage','invoices'].map(t=><button className={tab===t?'active':''} aria-pressed={tab===t} key={t} onClick={()=>setTab(t)}>{words(t)}</button>)}</div><div className="actions"><button onClick={()=>setShowImport(true)}>Import CSV</button><a className="button" href={`/api/export/${tab}`}>Export CSV</a><button className="primary" onClick={()=>onEdit({kind:tab as Editor['kind']})}>{tab==='mileage'?'Log mileage':tab==='invoices'?'Record invoice':'Add expense'}</button></div></div>
  {!rows.length?<Empty title={`No ${tab} recorded`}>Start with a record or import an existing CSV summary.</Empty>:<div className="record-list">{rows.map(row=><div className={`record-row ${row.status==='void'?'void':''}`} key={row.id}><span><strong>{tab==='expenses'?row.vendor:tab==='mileage'?row.vehicle:`${row.number} · ${row.customer}`}</strong><small>{row.date} · {tab==='expenses'?row.category:tab==='mileage'?row.purpose:row.source} · {words(row.status)}</small></span><span className="record-actions"><strong>{tab==='expenses'?dollars(row.amount_cents):tab==='mileage'?`${((Number(row.end_tenths)-Number(row.start_tenths))/10).toFixed(1)} mi`:dollars(row.total_cents)}</strong><button onClick={()=>onEdit({kind:tab as Editor['kind'],row})}>Edit</button>{tab==='expenses'&&(<button onClick={()=>onReceipt(row)}>{row.receipt_id?'Receipt':'Add receipt'}</button>)}</span></div>)}</div>}
  <section className="activity"><h2>Import history</h2>{!state.imports.length?<p className="muted">Reviewed file imports will appear here. No accounting app is connected for live synchronization.</p>:state.imports.map(b=><div className="record-row" key={b.id}><span><strong>{b.source} · {b.row_count} {b.kind}</strong><small>{b.created_at} UTC · {b.undone?'Undone':'Imported'}</small></span>{!b.undone&&<button onClick={()=>setUndo(b.id)}>Undo import</button>}</div>)}</section>
  {showImport&&<ImportPanel state={state} onClose={()=>setShowImport(false)} onSaved={onReload}/>}
  {undo&&<Modal title="Undo this import?" onClose={()=>!busy&&setUndo(null)}><p>This keeps the history and marks unedited imported records as void. It does not delete receipts or change your external accounting app.</p><ErrorText message={error}/><div className="form-actions"><button onClick={()=>setUndo(null)} disabled={busy}>Cancel</button><button className="primary" onClick={()=>{void undoBatch();}} disabled={busy}>{busy?'Working…':'Undo import'}</button></div></Modal>}</>;
}
