import {useState} from 'react';
import {api} from './api';
import {categories,statuses,money} from '../shared/validation';
import {type Editor,type State,type Row,words,today} from './types';
import {Modal,Field,Form,ErrorText} from './ui';

export function RecordEditor({editor,state,onClose,onSaved}:{editor:Editor;state:State;onClose:()=>void;onSaved:(id:string,kind:string)=>Promise<void>}) {
  const {kind,row}=editor,[error,setError]=useState(''),[busy,setBusy]=useState(false),[recordId]=useState(()=>row?.id??crypto.randomUUID());
  const value=(key:string,fallback:string|number='')=>String(row?.[key]??fallback);
  const owner=state.me.role==='owner';
  async function submit(data:FormData){setError('');setBusy(true);try{
    const result:Record<string,unknown>={...Object.fromEntries(data),id:recordId,version:row?.version};
    if(kind==='customers')result.archived=data.get('archived')==='on'?1:0;
    if(kind==='jobs')result.quoted_cents=money(String(data.get('quote')||'0'));
    if(kind==='expenses')result.amount_cents=money(String(data.get('amount')));
    if(kind==='invoices'){result.total_cents=money(String(data.get('total')));result.paid_cents=money(String(data.get('paid')||'0'));}
    if(kind==='mileage'){for(const [field,input] of [['start_tenths','start'],['end_tenths','end']]){const raw=String(data.get(input));if(!/^\d+(\.\d)?$/.test(raw))throw new Error('Use odometer readings with at most one decimal.');result[field]=Math.round(Number(raw)*10);}if(Number(result.end_tenths)<Number(result.start_tenths))throw new Error('Ending odometer must be at least the starting reading.');}
    await api(`${kind}${row?`/${row.id}`:''}`,{method:row?'PUT':'POST',body:JSON.stringify(result)});
    await onSaved(recordId,kind);onClose();
  }catch(e){setError(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);}}
  const jobSelect=<Field label="Job"><select name="job_id" defaultValue={value('job_id',editor.jobId??'')} required={!owner}><option value="">{owner?'Business expense / no job':'Choose a job'}</option>{state.jobs.filter(j=>j.status!=='archived').map(j=><option key={j.id} value={j.id}>{j.title}</option>)}</select></Field>;
  const input=(key:string,label:string,required=false,type='text',fallback='')=><Field label={label}><input name={key} type={type} defaultValue={value(key,fallback)} required={required} maxLength={key==='address'?400:250}/></Field>;
  const area=(key:string,label:string)=><Field label={label}><textarea name={key} rows={3} maxLength={key==='scope'?6000:2000} defaultValue={value(key)}/></Field>;
  return <Modal title={`${row?'Edit':'Add'} ${kind==='mileage'?'mileage':kind.slice(0,-1)}`} onClose={()=>!busy&&onClose()}><Form onSubmit={submit}><fieldset disabled={busy}>
    {kind==='customers'&&<>{input('name','Customer name',true)}<div className="form-grid">{input('phone','Phone',false,'tel')}{input('email','Email',false,'email')}</div>{input('address','Address')}{area('notes','Private notes')}{row&&<label className="check"><input type="checkbox" name="archived" defaultChecked={!!row.archived}/>Archive this customer</label>}</>}
    {kind==='jobs'&&<><Field label="Customer"><select name="customer_id" required defaultValue={value('customer_id')}><option value="">Choose a customer</option>{state.customers.filter(c=>!c.archived||c.id===row?.customer_id).map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></Field>{!state.customers.length&&<p>Add a customer from Customers before creating a job.</p>}{input('title','Job name',true)}{input('address','Job address')}<div className="form-grid"><Field label="Status"><select name="status" defaultValue={value('status','lead')}>{statuses.map(s=><option key={s} value={s}>{words(s)}</option>)}</select></Field>{input('scheduled_date','Scheduled date',false,'date')}</div>{area('scope','Work details visible to the crew')}{area('owner_notes','Private owner notes')}<Field label="Quoted amount ($)" hint="Owner only. A quote is not a payment."><input name="quote" inputMode="decimal" defaultValue={(Number(row?.quoted_cents||0)/100).toFixed(2)} required/></Field></>}
    {kind==='expenses'&&<>{jobSelect}<div className="form-grid">{input('date','Date',true,'date',today())}{input('vendor','Vendor',true)}</div><div className="form-grid"><Field label="Amount ($)"><input name="amount" inputMode="decimal" required defaultValue={row?(Number(row.amount_cents)/100).toFixed(2):''}/></Field><Field label="Category"><select name="category" defaultValue={value('category','Materials')}>{categories.map(c=><option key={c}>{c}</option>)}</select></Field></div>{area('notes','Notes')}{owner&&<Field label="Review status"><select name="status" defaultValue={value('status','submitted')}><option value="submitted">Submitted</option><option value="reviewed">Reviewed</option><option value="void">Void (keep record)</option></select></Field>}<p className="muted">Save the expense, then attach its receipt photo.</p></>}
    {kind==='mileage'&&<>{jobSelect}<div className="form-grid">{input('date','Date',true,'date',today())}{input('vehicle','Vehicle',true)}</div>{input('purpose','Trip purpose',true)}<div className="form-grid"><Field label="Starting odometer (miles)"><input name="start" inputMode="decimal" required defaultValue={row?Number(row.start_tenths)/10:''}/></Field><Field label="Ending odometer (miles)"><input name="end" inputMode="decimal" required defaultValue={row?Number(row.end_tenths)/10:''}/></Field></div>{row&&<Field label="Record status"><select name="status" defaultValue={value('status','recorded')}><option value="recorded">Recorded</option><option value="void">Void (keep record)</option></select></Field>}<p className="muted">Record work travel only. We do not calculate tax deductions.</p></>}
    {kind==='invoices'&&<>{jobSelect}<div className="form-grid">{input('number','Invoice number',true)}{input('date','Invoice date',true,'date',today())}</div>{input('customer','Customer name',true)}<div className="form-grid"><Field label="Invoice total ($)"><input name="total" inputMode="decimal" required defaultValue={row?(Number(row.total_cents)/100).toFixed(2):''}/></Field><Field label="Amount paid ($)"><input name="paid" inputMode="decimal" required defaultValue={(Number(row?.paid_cents||0)/100).toFixed(2)}/></Field></div>{input('source','Source',true,'text','Manual')}{row&&<Field label="Record status"><select name="status" defaultValue={value('status','recorded')}><option value="recorded">Recorded</option><option value="void">Void</option></select></Field>}<p className="muted">This records an existing invoice. It does not send a bill or collect a payment.</p></>}
    <ErrorText message={error}/><div className="form-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary" disabled={kind==='jobs'&&!state.customers.length}>{busy?'Saving…':'Save'}</button></div>
  </fieldset></Form></Modal>;
}
