import {useState} from 'react';
import type {State,Row} from './types';
import {post} from './api';
import {Modal,Form,Field,ErrorText} from './ui';
export function Team({state,onReload}:{state:State;onReload:()=>Promise<void>}) {
  const [adding,setAdding]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState<Row|null>(null);
  async function create(data:FormData){setBusy(true);setError('');try{await post('team',{name:data.get('name'),email:data.get('email')});await onReload();setAdding(false);setMessage('Crew member added. The administrator must also approve this exact email in Cloudflare Access before their first sign-in. No invitation email was sent.');}catch(e){setError(e instanceof Error?e.message:'Could not create account.');}finally{setBusy(false);}}
  async function access(){if(!confirm)return;setBusy(true);setError('');try{await post(`team/${confirm.id}/access`,{active:confirm.active?0:1});await onReload();setConfirm(null);}catch(e){setError(e instanceof Error?e.message:'Could not change access.');}finally{setBusy(false);}}
  return <><div className="section-heading"><p className="muted">Crew members see assigned work and their own submissions, not company finances.</p><button className="primary" onClick={()=>{setError('');setAdding(true);}}>Add crew member</button></div><ErrorText message={error}/>{message&&<p role="status">{message}</p>}<div className="record-list">{state.team.map(u=><div className="record-row" key={u.id}><span><strong>{u.name}</strong><small>{u.email} · {u.role==='owner'?'Owner':u.active?'Crew · Active':'Crew · Disabled'}</small></span>{u.role!=='owner'&&<div className="actions"><button disabled={busy} onClick={()=>{setError('');setConfirm(u);}}>{u.active?'Disable access':'Restore access'}</button></div>}</div>)}</div>
  {adding&&<Modal title="Add crew member" onClose={()=>!busy&&setAdding(false)}><Form onSubmit={create}><Field label="Name"><input name="name" required maxLength={120}/></Field><Field label="Email" hint="Their own personal or work email. No company email is required."><input name="email" type="email" autoComplete="off" required maxLength={254}/></Field><p className="muted">After adding them, ask the administrator to approve the same address in Cloudflare Access. They will sign in with an email code. No email is sent by this form.</p><ErrorText message={error}/><div className="form-actions"><button type="button" onClick={()=>setAdding(false)} disabled={busy}>Cancel</button><button className="primary" disabled={busy}>{busy?'Creating…':'Create account'}</button></div></Form></Modal>}
  {confirm&&<Modal title={confirm.active?'Disable this account?':'Restore this account?'} onClose={()=>!busy&&setConfirm(null)}><p>{confirm.active?'This immediately blocks dashboard requests. Their job history and submissions are kept. The administrator should also remove their Cloudflare approval.':'This restores dashboard permission. Cloudflare approval is also required, and the person must sign in again.'}</p><ErrorText message={error}/><div className="form-actions"><button onClick={()=>setConfirm(null)} disabled={busy}>Cancel</button><button className="primary" onClick={()=>{void access();}} disabled={busy}>{busy?'Saving…':'Confirm'}</button></div></Modal>}</>;
}
